# Generated by Django 4.0.3 on 2022-03-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('time_action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dioxide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('time_action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('time_action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('time_action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
